all:
  children:
    local:
      hosts:
        localhost:
          ansible_connection: local
          ansible_python_interpreter: auto_silent

    master_node:
      hosts:
        master-node_01:

    worker_node:
      hosts:
        worker-node_01:

    devices:
      hosts:
        master-node_01:
          ansible_host: "{{ vault_master_node_host }}"
        worker-node_01:
          ansible_host: "{{ vault_worker_node_host }}"
